### ISSUE TITLE
Dataloaders Generated Structs

### ISSUE THREAD

**Issue by mainawycliffe** [ridhamtarpara/go-graphql-demo#3]
Did you edit the generated userloader_gen.go manually to add reference to the correct struct(api.Users), or is there a way of passing the struct to use for users during creation?

**Comment by ridhamtarpara** [comment]
No it's generated file, but if you are using different version then it might be different

**Comment by mainawycliffe** [comment]
Yea, the latest version doesn't generate the structs, i think i will try and use type aliases and see if it works. Thanks.
