### ISSUE TITLE
Not able to run 'dep ensure' command

### ISSUE THREAD

**Issue by mayurvpatil** [ridhamtarpara/go-graphql-demo#5]
I'm new to GOLang and dep package. 

Installed dep package using 
`go get -u github.com/golang/dep/cmd/dep`
 
While executing `dep ensure` I'm getting error as 

> dep command not found

I'm using MacOs Mojave. 
This is definitely not an issue with your code but it would be great if you update Readme to prevent this.
 
Thanks.

**Comment by ridhamtarpara** [comment]
Updated the readme for installing dep
