### ISSUE TITLE
can't run server

### ISSUE THREAD

**Issue by adrien-barret** [ridhamtarpara/go-graphql-demo#6]
### Info 
system: osx mojave
go version: go version go1.13.4 darwin/amd64

### Reproduce: 
- mkdir -p $GOPATH/src/github.com/ridhamtarpara/go-graphql-demo/
- cd $GOPATH/src/github.com/ridhamtarpara/go-graphql-demo/
- git clone https://github.com/ridhamtarpara/go-graphql-demo.git .
- dep ensure
- go run server/server.go

### Error: 
panic: dial tcp [::1]:5432: connect: connection refused

goroutine 1 [running]:
main.checkErr(...)
	/Users/hk/workspace/golang/src/github.com/ridhamtarpara/go-graphql-demo/server/server.go:43
main.main()
	/Users/hk/workspace/golang/src/github.com/ridhamtarpara/go-graphql-demo/server/server.go:24 +0x4f9
exit status 2

**Comment by NavenduDuari** [comment]
I'm facing the same problem on windows.

**Comment by ridhamtarpara** [comment]
Updated the read me to resolve the error and also added improvements list.
